name: Ensure Clean Notebooks

on:
  push:
    paths:
      - '**/*.ipynb' # Trigger only when .ipynb files are modified
  pull_request:
    paths:
      - '**/*.ipynb' # Trigger only when .ipynb files are modified

jobs:
  clean-notebooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Strip notebook outputs
        run: |
          pip install nbstripout
          nbstripout --install
            find . -name "*.ipynb" -exec nbstripout {} \;

      - name: Ensure clean notebooks
        uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1
